version: '3.8'
services:
  postgresql:
    image: postgres:16
    container_name: sonarqube-postgresql
    environment:
      POSTGRES_USER: sonar_pg_user
      POSTGRES_PASSWORD: 0fNT0*MB0Di1
      POSTGRES_DB: bitnami_sonarqube
    volumes:
      - /opt/sonarqube/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube-network
    restart: always

  sonarqube:
    image: bitnami/sonarqube:10
    container_name: sonarqube
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql:5432/bitnami_sonarqube
      SONARQUBE_JDBC_USERNAME: sonar_pg_user
      SONARQUBE_JDBC_PASSWORD: 0fNT0*MB0Di1
      SONARQUBE_USERNAME: sonar
      SONARQUBE_PASSWORD: subbusonar@1234$
    volumes:
      - /opt/sonarqube:/bitnami/sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgresql
    networks:
      - sonarqube-network
    restart: always

networks:
  sonarqube-network:
    driver: bridge

------------------------------------------------------

# Steps to Deploy:-
1 Create Directories for Data Persistence:
 sudo mkdir -p /opt/sonarqube/postgresql_data
 sudo mkdir -p /opt/sonarqube

2 Set Correct Permissions:
sudo chown -R 1001:1001 /opt/sonarqube /opt/sonarqube/postgresql_data
3 Run Docker Compose: Navigate to the directory containing docker-compose.yml and run:
docker-compose up
docker-compose up -d


Access SonarQube: Open your browser and navigate to:
http://localhost:9000

Use the following credentials:
Username: sonar
Password: subbusonar@1234$


