prometheus.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: subu
  labels:
    app: prometheus
data:
  example.rules: |
    groups:
    - name: example
      rules:
       - alert: HighCPUUsage
         expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 90
         for: 1m
         labels:
           severity: warning
         annotations:
           summary: "High CPU usage detected"
           description: "CPU usage is {{ $value }}%"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: subu
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
       - static_configs:
          - targets: ['a9ebf10af726b44c1a12df07379f9f21-603559460.ap-south-1.elb.amazonaws.com:80']

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'nodeexporter'
        static_configs:
          - targets: ['ab289b1178ec74ccb961c06758c61935-1681188938.ap-south-1.elb.amazonaws.com:8080']
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: subu
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.32.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              readOnly: true
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules
              readOnly: true
             volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          emptyDir: {}
        - name: prometheus-rules
          configMap:
          name: prometheus-rules
          
  ---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: subu
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 80
      targetPort: 9090
  type: LoadBalancer        

