---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: subu
data:
  alertmanager.yml: |-
    global:
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: "kovvurusubbu7@gmail.com"
      smtp_auth_username: "kovvurusubbu7@gmail.com"
      smtp_auth_password: Subbu@786
      smtp_require_tls: true
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: "kovvurusbbu3@gmail.com"
            from: "kovvurusubbu7@gmail.com"
            smarthost: 'smtp.gmail.com:587'
            auth_username: "kovvurusubbu7@gmail.com"
            auth_password: "Subbu@786"
            headers:
              Subject: '{{ template "prometheus.default.subject" . }}'
            html: '{{ template "prometheus.default.html" . }}'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: subu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.22.2
        args:
        - '--config.file=/etc/config/alertmanager.yml'
        - '--storage.path=/alertmanager'
        ports:
        - name: web
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: alertmanager-data
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager-data
        emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: subu
spec:
  selector:
    app: alertmanager
  ports:
  - name: web
    port: 80
    targetPort: 9093
  type: LoadBalancer


---  
