---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: subu
type: Opaque
data:
  admin-password: YWRtaW4xMjM= # Base64-encoded password "admin123"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: subu
data:
  grafana.ini: |-
    [server]
    http_port = 3000
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true
    [database]
    type = sqlite3
    path = /data/grafana.db
    [analytics]
    check_for_updates = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: subu
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.3.3
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: admin-password
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-data
              mountPath: /data
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-data
          emptyDir: {}



---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: subu
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
