---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: subu
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: node
      port: 8080
      targetPort: 9100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: subu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: bonomat/nodejs-hello-world
        ports:
        - containerPort: 3000
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
