install docker:

apt update -y
apt install  docker.io -y

compose_install
-----------------
sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
docker-compose –version
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

 Create MongoDB Data Directory
-------------------------------
sudo mkdir -p /mnt/mongodb
Mount the Disk (Optional)
lsblk

sudo mkfs.ext4 /dev/sdb1
sudo mount /dev/sdb1 /mnt/mongodb

sudo nano /etc/fstab


Step 5: Set Permissions"
-----------------------------
sudo chown -R root:root ~/mongodb/config
sudo chmod -R 777 ~/mongodb/config

ls -ld ~/mongodb/config

nano ~/mongodb/config/mongo.conf
storage:
  dbPath: /data/db
  journal:
    enabled: true

net:
  bindIp: 0.0.0.0
  port: 55017

security:
  authorization: enabled

systemLog:
  destination: file
  path: /data/logs/mongod.log
  logAppend: true


---
Step 9: Docker Compose Setup for MongoDB
--
version: '3.7'

services:
  mongodb:
    image: mongo:3.6.0
    container_name: mongodb
    restart: always
    ports:
      - "55017:55017"
    volumes:
      - /mnt/mongodb:/data/db
      - ./config/mongo.conf:/etc/mongo.conf
      - ./logs:/data/logs
    command: mongod --config /etc/mongo.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

cd ~/mongodb
docker-compose up -d


Step 11: Verify MongoDB is Running
docker ps 

Step 12: Verify MongoDB Logs
tail -f ~/mongodb/logs/mongod.log
ls -l /mnt/mongodb


