elastic_service.yaml
====================

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
    
    
 elasticsearch.yaml
 ===================
 
 apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
      app: elasticsearch
spec:
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
    - containerPort: 9200
    - containerPort: 9300
    env:
    - name: discovery.type
      value: single-node
      
      
 kibana.yaml
 ===========
 
apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
     app: kibana
spec:
  containers:
  - name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
    - containerPort: 5601
    env:
    - name: ELASTICSEARCH_HOSTS
      value: http://elasticsearch-service:9200
      
      
