pl  create the vm
-----------------
1 sudo apt update -y
2 sudo apt install  docker.io -y
# install the docker-compose 
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version


create the folder:-
-------------------
mkdir kafka
cd kafka 
vim docker-compose.yml
------------------------
version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    restart: unless-stopped
    networks:
      - kafka_network
    ports:
      - "9092:9092"
    volumes:
      - /opt/kafka/data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

networks:
  kafka_network:
    driver: bridge

volumes:
  kafka_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/kafka/data
      o: bind

---------------------------------------------------------------

Create the directory and set permissions:
----
mkdir -p /opt/kafka/data
chmod 0777 /opt/kafka/data
--
Start the Kafka service using Docker Compose:
--
docker-compose up 
docker-compose up -d
